### ISSUE TITLE
本リリースレビュー

### ISSUE THREAD

**Issue by tmtkzk0823** [inoserisa/jimotter#124]
以下、レビュー内容になりますのでご確認ください。

### 技術
- JavaScriptで変数を定義する時`var`を使用していますが、こちらはできるだけ、`let, const`を使用するようにしましょう。
- Rails側は`rubocop`,  JavaScript側は`prettier`などを入れて、リントチェックをすると見た目も整ったコードになるかと思います。

### ユーザビリティ
- 現状、投稿一覧に表示されている各投稿は、投稿者の名前がリンクになっているかと思いますが、投稿全体がリンクになるようにしてもいいかと思いました。

以上です！
UIUXに関してはかなり綺麗に整っているかと思います！

上記レビューに関して、質問などありましたらスレッドに記載いただいてご連絡ください！

**Comment by inoserisa** [comment]
レビューありがとうございます！

取り急ぎ、投稿一覧の各カード全体をリンク化しました！ご指摘ありがとうございます！
JavaScriptの変数とリントチェックも追って修正したいと思います！
