### ISSUE TITLE
issueベースの開発レビュー依頼

### ISSUE THREAD

**Issue by inoserisa** [inoserisa/jimotter#21]
issueのレビューよろしくお願いいたします。

## MVPリリースで実装予定の機能
- [x] ユーザー登録
- [x] ログイン(devise)
- [x] マイページ
- [x] ユーザー情報の変更機能（ユーザー名、メールアドレス、パスワード、地域、アイコン）
- [x] あるあるの投稿機能、投稿の削除機能
- [x] 選択肢から都道府県・市区町村を指定して投稿する機能
- [x] 都道府県・市区町村を指定して検索(ransack)
- [x] トップ画面に新着一覧
- [x] 投稿にコメント(Ajax)
- [x] 画像アップデート(ActiveStorage)
- [x] 「このアプリについて」ページ

### プロジェクト
https://github.com/users/inoserisa/projects/1

|Todo|必要機能|ストーリーポイント|
|----|----|----|
|アプリケーションの雛形作成|Gemfileの記載<br>データベース・モデルの作成|2|
|トップ画面|ビューファイルの作成<br>新着投稿一覧の表示|3|
|ログイン|ログイン画面のビューファイル作成<br>ログイン機能の実装|3|
|新規登録画面|仮登録メールアドレス入力画面<br>仮登録メール送信完了画面<br>メールURLクリック後画面|2|
|新規登録メール送信機能|新規登録メールの送信機能|5|
|マイページ|マイページ画面作成<br>マイページに自分の投稿一覧表示|3|
|プロフィール編集|アイコンの変更<br>ユーザー名の変更<br>設定地域を変更|3|
|メールアドレス変更|メールアドレス変更ビューファイル<br>メールアドレス変更機能|3|
|パスワード変更|パスワード変更ビューファイル<br>パスワード変更機能|3|
|あるある投稿|投稿機能<br>都道府県・市区町村を絞り込んで投稿|5|
|投稿詳細|投稿詳細のビューファイル<br>投稿削除|3|
|画像アップロード機能|画像アップロード機能<br>投稿に表示|3|
|コメント|コメント機能<br>非同期通信化|3|
|検索|投稿を検索<br>地域で絞り込んで検索|5|
|退会|ユーザーの削除|2|
|このアプリについて|ビューファイル作成|1|
|サイトデザイン調整|CSSデザイン調整|3|
|合計|　|52|

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

---

■MVP時には不要と感じたもの（本リリース時で良いと思ったもの）
・新規登録メール送信機能
・プロフィール編集
・メールアドレス変更
・パスワード変更
・退会

デプロイのカードも用意しておきましょう。また、rails new 後にすぐにデプロイするようにしましょう。
