### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by inoserisa** [inoserisa/jimotter#53]
## 各種情報
サービス名：Jimotter(ジモッター)-地域あるある投稿アプリ-
サービスURL：https://www.jimotter.com
サービス概要：
都道府県と市区町村を指定してあるあるやエピソードを投稿。
投稿地域に紐づいて詳細画面で地図にピンがささる。投稿にコメントができる。
また、他の人に質問もでき、回答者は地域を選択して回答できる。
## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ユーザー登録
- [x] ログイン(devise)
- [x] マイページ
- [x] あるあるの投稿機能、投稿の削除機能
- [x] 選択肢から都道府県・市区町村を指定して投稿する機能
- [x] 都道府県・市区町村を指定して検索(ransack)
- [x] トップ画面に新着一覧
- [x] 投稿にコメント(Ajax)
- [x] 「このアプリについて」ページ

#### 本リリースに移行
- ユーザー情報の変更機能（ユーザー名、メールアドレス、パスワード、地域、アイコン）
- 画像アップデート(ActiveStorage)

#### 本リリース予定だったが実装した機能
- ページネーション機能(kaminari)
- 共有ボタン(X等)
- パスワードリセット

#### READMEに記載していなかったが追加した機能
- 投稿詳細画面の地図表示
- 独自ドメイン取得

## サービスイメージがわかるようなスクリーンショット等
[![Image from Gyazo](https://i.gyazo.com/5e192cd6a143b79c228b748b47c1b8ae.png)](https://gyazo.com/5e192cd6a143b79c228b748b47c1b8ae)

[![Image from Gyazo](https://i.gyazo.com/290bca948af12bc983e65f3c6ffd0931.png)](https://gyazo.com/290bca948af12bc983e65f3c6ffd0931)

**Comment by shota-hope** [comment]
提出ありがとうございます。

- ページネーション機能が確認できなかったので、ローカルで大丈夫ですので画面録画をして動作をみせていただけますでしょうか？
- 都道府県を検索後の画面で、県を再選択後、市のセレクトが更新されないバグがあったのでご対応をお願いできますでしょうか。
- [![Image from Gyazo](https://i.gyazo.com/27cab056f08301c96775b029b1dc8d5d.gif)](https://gyazo.com/27cab056f08301c96775b029b1dc8d5d)
- その他は問題ありませんでした！(見やすく使いやすいUIでいいですね)

ご確認よろしくお願いいたします。

**Comment by inoserisa** [comment]
レビューありがとうございます。

・検索結果の画面で、市区町村が更新されないバグを修正いたしました。お気づきいただきありがとうございます。
[![Image from Gyazo](https://i.gyazo.com/61f9fe410814445b26e94b4adbaa3a52.gif)](https://gyazo.com/61f9fe410814445b26e94b4adbaa3a52)

・ページネーションの表示が、投稿と質問の一覧ページに10件以上ある場合表示する設定にしていて、10件未満だったため表示されていませんでした。現在10件以上になったため表示されています。失礼いたしました。
[![Image from Gyazo](https://i.gyazo.com/0f850c045eb6fd95c044bf3868190516.gif)](https://gyazo.com/0f850c045eb6fd95c044bf3868190516)

また、投稿ありがとうございます。
鶴巻温泉駅面白いです笑

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
